### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by aacunha** [priyadi/roundcube-converse.js-xmpp-plugin#33]
My installation of plugin works fine, but only in english. The translation on js/converse.min.js dont loads.

My roundcube/config/main.inc.php:
$rcmail_config['language'] = pt_BR;

Roundcube version: 0.9.5

![captura de tela de 2014-07-24 17 23 59](https://cloud.githubusercontent.com/assets/5031111/3694258/77454af8-1370-11e4-969f-2d9734515de1.png)

**Comment by dashlan** [comment]
Hi,
I am having the same problem. It´s only working for language EN_US. How did you solve the problem ?

**Comment by dashlan** [comment]
Sorry,
I didn´t see fabiodepin correction.
It was a simple solution, just replace the word "pt-br" to "pt_BR" on file js/converse.min.js

**Comment by aacunha** [comment]
@dashlan thanks! Works fine now!
