### ISSUE TITLE
Error with nginx

### ISSUE THREAD

**Issue by aacunha** [priyadi/roundcube-converse.js-xmpp-plugin#46]
I have a lot of erros in nginx error.log:

3091280 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 10.30.1.223, server: localhost, request: "POST /http-bind HTTP/1.1", upstream: "http://127.0.1.1:5280/http-bind/", host: "xxx.xxx.edu.br", referrer: "https://xxx.xxx.edu.br/?_task=mail&_mbox=INBOX"

But i dont see any erros using the application.

ambient:
nginx 1.2.1
mysql 5.5
roundcube 1.1.1

**Comment by mckaygerhard** [comment]
the "http://127.0.1.1:5280/http-bind/" are not proper maskaring, u must configure a reverse-proxy for the path "/http-bind/" and dont forgive are not only "/http-bind/" also "/http-bind" too

and also in the jabber server must configure to acept multiple connectionsa and enabled the bind module (that depends on the jabber software)

i have this errors in my combination (lighttpd+ejabberd+conversation) when i not property setup the reverse proxy for the bind (including if behing a firewall or not)

**Comment by aacunha** [comment]
everything ok with reverse proxy in the same domain of roundcube.
