### ISSUE TITLE
Update converse.js to last version

### ISSUE THREAD

**Issue by MurzNN** [priyadi/roundcube-converse.js-xmpp-plugin#54]
Seems that your plugin have too old version of converse.js without MAM support. Can you update Converse.JS to last version? Thanks!

**Comment by devurandom** [comment]
Could you please try https://github.com/devurandom/roundcube-converse.js-xmpp-plugin and see if that works for you? This ad-hoc fork was created to use converse.js 2.0.0 and it works well for me so far.

**Comment by MurzNN** [comment]
Thanks, devurandom updated version works well and loads chat archive via MAM!
